apiVersion: kafka.infra.doodle.com/v1beta1
kind: KafkaTopic
metadata:
  name: my-topic
  namespace: default
spec:
  address: "kafka-client.default:9092"
  config:
    cleanupPolicy: delete
    deleteRetentionMs: 604800000
    minInsyncReplicas: 2
  partitions: 16
  replicationFactor: 3
